# Default values for unit-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  requestsCpu: "0.1"
  requestsMemory: "256M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "unit"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  appName: "unit"
  configmap: "unit-config"
  onPremEnabled: false
  domain: ""
