variables:
  IBM_BUILD_SUBDIR: provider/unit-ibm/unit-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/unit_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py

  AWS_BUILD_SUBDIR: provider/unit-aws/build-aws
  AWS_TEST_SUBDIR: testing/unit_test_aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: unit
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: HELM
  AWS_EKS_DEPLOYMENT_NAME: os-unit

  AZURE_SERVICE: unit
  AZURE_BUILD_SUBDIR: provider/unit-azure/unit-aks
  AZURE_TEST_SUBDIR: testing/unit_test_azure
  AZURE_TEST_TYPE: python
  SHARE_NAME: unit

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-python-test.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-python.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - local: "devops/gcp/pipeline/override-stages.yml"
