variables:
  IBM_BUILD_SUBDIR: provider/unit-ibm/unit-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/unit_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py
  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-unit-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-unit-deploy

  AWS_BUILD_SUBDIR: provider/unit-aws/build-aws
  AWS_TEST_SUBDIR: testing/unit_test_aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: unit
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-unit

  AZURE_SERVICE: unit
  AZURE_BUILD_SUBDIR: provider/unit-azure/unit-aks
  AZURE_TEST_SUBDIR: testing/unit_test_azure
  AZURE_TEST_TYPE: python
  SHARE_NAME: unit

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-python-test.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-python.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: m18-pipeline-update-mm

  - local: "devops/gc/pipeline/override-stages.yml"
