variables:
  # --- osdu-gcp specific variables ---
  OSDU_GCP_SERVICE: unit
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-unit
  OSDU_GCP_INT_TEST_TYPE: python
  OSDU_GCP_PYTHON_INT_TEST_SUBDIR: testing/unit_test_gcp
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.google_audiences=$GOOGLE_AUDIENCE --set data.unit_catalog_bucket=$OSDU_GCP_UNIT_CATALOG_BUCKET"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: "--set data.google_audiences=$GOOGLE_AUDIENCE --set data.unit_catalog_bucket=$OSDU_GCP_UNIT_CATALOG_BUCKET"
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s"
  OSDU_GCP_HELM_CONFIG_SERVICE: unit-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: unit-deploy
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_HELM_DEPLOYMENT_DIR: "devops/gcp/deploy"
  OSDU_GCP_HELM_CONFIG_DIR: "devops/gcp/configmap"
  # --- end of osdu-gcp specific variables ---

  IBM_BUILD_SUBDIR: provider/unit-ibm/unit-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/unit_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py

  AWS_BUILD_SUBDIR: provider/unit-aws/build-aws
  AWS_TEST_SUBDIR: testing/unit_test_aws
  AWS_SERVICE: unit
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-unit

  AZURE_SERVICE: unit
  AZURE_BUILD_SUBDIR: provider/unit-azure/unit-aks
  AZURE_TEST_SUBDIR: testing/unit_test_azure
  AZURE_TEST_TYPE: python
  SHARE_NAME: unit

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-python-test.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

osdu-gcp-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_UNIT_HOSTNAME

osdu-gcp-dev2-test-python:
  variables:
    VIRTUAL_SERVICE_HOST_NAME: $OSDU_GCP_UNIT_HOSTNAME
