variables:
  IBM_BUILD_SUBDIR: provider/unit-ibm/unit-ocp
  IBM_INT_TEST_PY_SUBDIR: testing/unit_test_ibm
  IBM_INT_TEST_PY_FILE: run_test.py
  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-unit-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-unit-deploy

  AWS_BUILD_SUBDIR: provider/unit-aws/build-aws
  AWS_TEST_SUBDIR: testing/unit_test_aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: unit
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-unit

  AZURE_SERVICE: unit
  AZURE_BUILD_SUBDIR: provider/unit-azure/unit-aks
  AZURE_TEST_SUBDIR: testing/unit_test_azure
  AZURE_TEST_TYPE: python
  SHARE_NAME: unit
  AZURE_SKIP_INTEGRATION_TEST: 'true'
  SERVICE_JAVA_VERSION: "17"
.maven:
  image: maven:3.9.3-eclipse-temurin-17
  tags: ['osdu-medium']
  variables:
    MAVEN_REPO_PATH: "$CI_PROJECT_DIR/.m2/repository"
    MAVEN_CLI_OPTS: "--batch-mode --settings=$CI_PROJECT_DIR/.mvn/community-maven.settings.xml"
gemnasium-maven-dependency_scanning:
  variables:
    DS_JAVA_VERSION: 17


include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-python-test.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-python.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - local: "devops/gc/pipeline/override-stages.yml"

azure_containerize:
  variables:
    AZURE_CONTAINERIZE_REPOSITORY: "-b jdk-17 https://gitlab-ci-token:${CI_JOB_TOKEN}@community.opengroup.org/osdu/platform/deployment-and-operations/base-containers-azure/service-base-image"

azure_test:
  image: community.opengroup.org:5555/osdu/platform/deployment-and-operations/base-containers-azure/azure-maven17:v0.0.1

aws-test-java:
  image: $CI_REGISTRY/osdu/platform/deployment-and-operations/base-containers-aws/aws-maven/aws-maven:v2.0

fossa-analyze:
  image: $CI_REGISTRY/divido/fossa-with-cache:v0.9-jdk17
fossa-check-notice:
  image: $CI_REGISTRY/divido/fossa-with-cache:v0.9-jdk17


