variables:
  # --- osdu gcp specific variables ---
  OSDU_GCP_SERVICE: unit
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-unit
  OSDU_GCP_UNIT_CATALOG_BUCKET: nice-etching-277309-unit-catalog-bucket
  OSDU_GCP_ENV_VARS: ENTITLEMENT_URL=$OSDU_GCP_ENTITLEMENTS_URL,UNIT_CATALOG_BUCKET=$OSDU_GCP_UNIT_CATALOG_BUCKET
  OSDU_GCP_PORT: 8080
  # --- end of osud gcp specific variables --- 

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: 'cloud-providers/osdu-gcp-cloudrun.yml'

