apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: os-unit-service
deploy:
  kubectl:
    manifests:
      - provider\unit-azure\unit-aks\istio\destination-rule.yaml
      - provider\unit-azure\unit-aks\istio\gateway.yaml
      - provider\unit-azure\unit-aks\istio\virtualservice-v2.yaml
      - provider\unit-gc\unit-gke\istio\destination-rule.yaml
      - provider\unit-gc\unit-gke\istio\gateway.yaml
      - provider\unit-gc\unit-gke\istio\virtualservice-v2.yaml
