service: os-unit-gae

runtime: java
env: flex

runtime_config:
  jdk: openjdk8

api_version: 1
threadsafe: yes

resources:
  cpu: 2
  memory_gb: 2.4
  disk_size_gb: 20

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.5

handlers:
- url: /.*
  script: this field is required, but ignored

# liveness_check:
#   path: '/_ah/liveness_check'
#   timeout_sec: 4
#   check_interval_sec: 10
#   failure_threshold: 3
#   success_threshold: 2
#   initial_delay_sec: 600

# readiness_check:
#   path: '/_ah/readiness_check'
#   timeout_sec: 4
#   check_interval_sec: 5
#   failure_threshold: 2
#   success_threshold: 2
#   app_start_timeout_sec: 600

env_variables:
  ENTITLEMENT_URL:  ENTITLEMENT_URL_PLACE_HOLDER
