# Default values for unit-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  logLevel: "ERROR"
  tier: ""
  autoscaling: true

data:
  logLevel: ""
  entitlementsHost: "http://entitlements"
  requestsCpu: "5m"
  requestsMemory: "275Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "unit"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  appName: "unit"
  configmap: "unit-config"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue" #Could be AverageValue or Value
  targetValue: 120 #60 rps
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 70
  tokensPerFill: 70
  fillInterval: "1s"
