# Default values for unit-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false

data:
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  requestsCpu: "10m"
  requestsMemory: "350Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "unit"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  appName: "unit"
  configmap: "unit-config"

istio:
  proxyCPU: "10m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
