apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: osdu
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
    spec:
      volumes:
      - name: azure-keyvault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: "init-unit-catalog"
        image: "{{ .Values.catalog.repository }}:{{ .Values.catalog.tag }}"
        imagePullPolicy: {{ .Values.catalog.pullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/unit_catalogs              
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}/{{ .Chart.Name }}-{{ .Values.image.branch }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/unit/_ah/readiness_check
            port: 80
        volumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
        - name: shared-data
          mountPath: /mnt/unit_catalogs          
        env:
        - name: spring_application_name
          value: unit-service
        - name: server.servlet.contextPath
          value: /api/unit/
        - name: server_port
          value: "80"
        - name: ACCEPT_HTTP  # TEMPORARY UNTIL HTTPS
          value: "true"
        - name: KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-properties
              key: ENV_KEYVAULT
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: tenantid
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientpassword
        - name: appinsights_key
          valueFrom:
            secretKeyRef:
              name: central-logging
              key: appinsights
        - name: aad_client_id
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: application-appid
        - name: ENTITLEMENT_URL
          value: http://entitlements-azure/entitlements/v1
        - name: azure_istioauth_enabled
          value: "true"
