apiVersion: apps/v1
kind: Deployment
metadata:
  name: "unit-aks"
  namespace: {{ .Values.namespace }}  
  labels:
    app: "unit-aks"
    version: v2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "unit-aks"
      version: v2
  template:
    metadata:
      labels:
        app: "unit-aks"
        version: v2
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: shared-data
            mountPath: /mnt/unit_catalogs
          ports:
            - name: http
              containerPort: {{ .Values.service.http.targetPort }}
            - name: https
              containerPort: {{ .Values.service.https.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENTITLEMENT_URL
              value: "{{.Values.service.entitlement.url}}"
            - name: client-id
              value: "{{.Values.service.client.url}}"
      initContainers:
      - name: "init-unit-catalog"
        image: "{{ .Values.catalogs.repository }}:{{ .Values.catalogs.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/unit_catalogs
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
