global:
  replicaCount: 1

image:
  repository: ${CONTAINER_REGISTRY_NAME}.azurecr.io/unit-service
  tag: latest
  pullPolicy: Always

catalog:
  repository: ${CONTAINER_REGISTRY_NAME}.azurecr.io/unit-catalog-data
  tag: v2
  pullPolicy: Always


