global:
  replicaCount: 1
  maxReplicaCount: 1
  minReplicaCount: 1
  nodepool: services
  isAutoscalingEnabled: false

image:
  repository: community.opengroup.org:5555/osdu/platform/system/reference/unit-service
  tag: latest
  pullPolicy: Always

istioDnsHost: "contoso.com"

env: demo

featureFlag:
  resourceLimits:
    enabledEnvs:
    - demo
  hpa:
    enabledEnvs: []
