global:
  replicaCount: 1

image:
  imagePullSecrets: acr

app:
  repository: delfi.azurecr.io/unit-app
  tag: latest
  pullPolicy: Always

catalog:
  repository: delfi.azurecr.io/unit-catalogs
  tag: v2
  pullPolicy: IfNotPresent


