apiVersion: apps/v1
kind: Deployment
metadata:
  name: "os-unit-service"
  labels:
    app: "os-unit-service"
    version: v2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "os-unit-service"
      version: v2
  template:
    metadata:
      labels:
        app: "os-unit-service"
        version: v2
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository }}os-unit-app:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: shared-data
            mountPath: /mnt/unit_catalogs
          ports:
            - name: http
              containerPort: {{ .Values.service.http.targetPort }}
            - name: https
              containerPort: {{ .Values.service.https.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: os-service-config
      initContainers:
      - name: "init-unit-catalog"
        image: "{{ .Values.repository }}unit-catalogs:{{ .Values.tag }}"
        imagePullPolicy: {{ .Values.image.catalogs.pullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/unit_catalogs
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
