name: Release Management

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

# Add workflow-level permissions
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-initialization:
    name: "🔍 Check Repository State"
    runs-on: ubuntu-latest
    outputs:
      initialized: ${{ steps.check.outputs.initialized }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        
      - name: "Verify Initialization Status"
        id: check
        run: |
          # Check repository variable instead of file
          if [ "${{ vars.INITIALIZATION_COMPLETE }}" = "true" ]; then
            echo "initialized=true" >> $GITHUB_OUTPUT
          else
            echo "initialized=false" >> $GITHUB_OUTPUT
          fi
          
  release-please:
    name: "📦 Create Release"
    needs: check-initialization
    if: needs.check-initialization.outputs.initialized == 'true'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      - name: "Generate Release PR"
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: .release-please-config.json
          
  tag-with-upstream:
    name: "🏷️ Update Release Tags"
    needs: [check-initialization, release-please]
    if: needs.check-initialization.outputs.initialized == 'true' && needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: "Fetch Upstream Version"
        run: |
          git remote add upstream ${{ vars.UPSTREAM_REPO_URL }}
          git fetch upstream --tags
          UPSTREAM_VERSION=$(git describe --tags --abbrev=0 upstream/main 2>/dev/null || echo "v0.0.0")
          echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> $GITHUB_ENV
          
      - name: "Update Release Tags"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Get the latest release tag
          RELEASE_TAG=$(gh release list -L 1 | cut -f 3)
          
          # Create new tag with upstream reference
          NEW_TAG="${RELEASE_TAG}-upstream-${UPSTREAM_VERSION}"
          git tag -d $RELEASE_TAG
          git push --delete origin $RELEASE_TAG
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
          # Update release with upstream information
          gh release edit $RELEASE_TAG \
            --tag $NEW_TAG \
            --notes "$(gh release view $RELEASE_TAG --json body -q .body)

            Upstream Version: ${UPSTREAM_VERSION}" 