trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - /provider/unit-gc
      - /provider/unit-aws
      - /provider/unit-ibm

resources:
  repositories:
    - repository: FluxRepo
      type: git
      name: k8-gitops-manifests
    - repository: TemplateRepo
      type: git
      name: infra-azure-provisioning

variables:
  - group: "Azure - OSDU"
  - group: "Azure - OSDU Secrets"

  - name: serviceName
    value: "unit-service"
  - name: chartPath
    value: "devops/azure/chart"
  - name: valuesFile
    value: "devops/azure/chart/helm-config.yaml"
  - name: "MANIFEST_REPO"
    value: $[ resources.repositories['FluxRepo'].name ]
  - name: "MAVEN_CACHE_FOLDER"
    value: $(Pipeline.Workspace)/.m2/repository

stages:
  - template: /devops/build-stage.yml@TemplateRepo
    parameters:
      mavenGoal: "package"
      mavenPublishJUnitResults: true
      serviceCoreMavenOptions: "-P unit-core --settings .mvn/community-maven.settings.xml -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
      mavenOptions: "-P unit-azure --settings .mvn/community-maven.settings.xml -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
      copyFileContents: |
        pom.xml
        maven/settings.xml
        provider/unit-azure/unit-aks/pom.xml
        provider/unit-azure/unit-aks/target/unit-aks-*.jar
      copyFileContentsToFlatten: ""
      mavenSettingsFile: "./maven/settings.xml"
      serviceBase: ${{ variables.serviceName }}
      testingRootFolder: "testing"
      chartPath: ${{ variables.chartPath }}

  - template: /devops/deploy-stages.yml@TemplateRepo
    parameters:
      serviceName: ${{ variables.serviceName }}
      chartPath: ${{ variables.chartPath }}
      valuesFile: ${{ variables.valuesFile }}
      testCoreMavenPomFile: ""
      testCoreMavenOptions: ""
      skipDeploy: ${{ variables.SKIP_DEPLOY }}
      skipTest: "true"
      runPythonTest: "true"
      testPythonFilePath: "testing/unit_test_azure"
      testPythonFile: "run-integration-tests.sh"
      providers:
        - name: Azure
          environments: ["demo"]
