
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - /provider/unit-gcp


resources:
  repositories:
  - repository: FluxRepo
    type: git
    name: r3-gitops-manifests
  - repository: TemplateRepo
    type: git
    name: r3-infra-azure-provisioning


variables:
  - group: 'R3MVP - Azure - OSDU'
  - group: 'R3MVP - Azure - OSDU Secrets'

  - name: serviceName
    value: "unit-service"
  - name: chartPath
    value: "devops/azure/chart"
  - name: valuesFile
    value: "devops/azure/chart/helm-config.yaml"
  - name: 'MANIFEST_REPO'
    value: $[ resources.repositories['FluxRepo'].name ]


stages:

  - template: /devops/build-stage.yml@TemplateRepo
    parameters:
      mavenGoal: 'package'
      mavenPublishJUnitResults: true
      serviceCoreMavenOptions: ''
      mavenOptions: ''
      copyFileContents: |
        pom.xml
        maven/settings.xml
        provider/unit-azure/unit-aks/pom.xml
        provider/unit-azure/unit-aks/target/unit-aks-*.jar
      copyFileContentsToFlatten: ''
      mavenSettingsFile: './maven/settings.xml'
      serviceBase: ${{ variables.serviceName }}
      testingRootFolder: 'testing'
      chartPath: ${{ variables.chartPath }}

  - template: /devops/deploy-stages.yml@TemplateRepo
    parameters:
      serviceName: ${{ variables.serviceName }}
      chartPath: ${{ variables.chartPath }}
      valuesFile: ${{ variables.valuesFile }}
      testCoreMavenPomFile: ''
      testCoreMavenOptions: ''
      skipDeploy: ${{ variables.SKIP_DEPLOY }}
      skipTest: 'true'
      providers:
        -  name: Azure
           environments: ['dev']
